from __future__ import annotations

from MAKSIMAR_SERVER.DASHBOARD_READ_ONLY_VIEWS.final_memory_map.final_memory_map_models import (
    FinalMemoryMap,
    FinalMemoryMapEdge,
    FinalMemoryMapNode,
)


def build_final_memory_graph() -> FinalMemoryMap:
    nodes = (
        FinalMemoryMapNode(
            node_id="memory_self_readability",
            label="JARVIS Memory Self-Readability",
            node_kind="memory_layer",
            source_path="MAKSIMAR_CORE_LIB/memory_engine/self_readability",
            read_only=True,
            dashboard_visible=True,
            canonical_write_allowed=False,
            runtime_mutation_allowed=False,
            node_ready=True,
        ),
        FinalMemoryMapNode(
            node_id="memory_drift_detection",
            label="Memory Drift / Contradiction Candidates",
            node_kind="memory_layer",
            source_path="MAKSIMAR_CORE_LIB/memory_engine/drift_detection",
            read_only=True,
            dashboard_visible=True,
            canonical_write_allowed=False,
            runtime_mutation_allowed=False,
            node_ready=True,
        ),
        FinalMemoryMapNode(
            node_id="mempalace_read_only_adapter",
            label="MemPalace Read-only Subordinate Backend",
            node_kind="backend_adapter",
            source_path="MAKSIMAR_SERVER/CONTROL_PLANE/memory_routing/adapters",
            read_only=True,
            dashboard_visible=True,
            canonical_write_allowed=False,
            runtime_mutation_allowed=False,
            node_ready=True,
        ),
        FinalMemoryMapNode(
            node_id="memory_sync",
            label="Shell / Client / Multi-node Memory Sync",
            node_kind="governance_layer",
            source_path="MAKSIMAR_SERVER/MEMORY_SYNC",
            read_only=True,
            dashboard_visible=True,
            canonical_write_allowed=False,
            runtime_mutation_allowed=False,
            node_ready=True,
        ),
        FinalMemoryMapNode(
            node_id="project_artifact_memory",
            label="Project Artifact Memory",
            node_kind="evidence_layer",
            source_path="MAKSIMAR_CORE_LIB/project_artifact_memory",
            read_only=True,
            dashboard_visible=True,
            canonical_write_allowed=False,
            runtime_mutation_allowed=False,
            node_ready=True,
        ),
        FinalMemoryMapNode(
            node_id="enterprise_regulatory_memory",
            label="Enterprise Regulatory Memory",
            node_kind="governance_layer",
            source_path="MAKSIMAR_CORE_LIB/enterprise_memory_domains",
            read_only=True,
            dashboard_visible=True,
            canonical_write_allowed=False,
            runtime_mutation_allowed=False,
            node_ready=True,
        ),
        FinalMemoryMapNode(
            node_id="final_memory_dashboard",
            label="Final Dashboard Memory Map",
            node_kind="dashboard_view",
            source_path="MAKSIMAR_SERVER/DASHBOARD_READ_ONLY_VIEWS/final_memory_map",
            read_only=True,
            dashboard_visible=True,
            canonical_write_allowed=False,
            runtime_mutation_allowed=False,
            node_ready=True,
        ),
    )

    edges = (
        FinalMemoryMapEdge(
            edge_id="edge_self_read_to_dashboard",
            from_node_id="memory_self_readability",
            to_node_id="final_memory_dashboard",
            relation="explains_source_usage",
            read_only_relation=True,
            edge_ready=True,
        ),
        FinalMemoryMapEdge(
            edge_id="edge_drift_to_dashboard",
            from_node_id="memory_drift_detection",
            to_node_id="final_memory_dashboard",
            relation="exposes_contradiction_candidates",
            read_only_relation=True,
            edge_ready=True,
        ),
        FinalMemoryMapEdge(
            edge_id="edge_mempalace_to_dashboard",
            from_node_id="mempalace_read_only_adapter",
            to_node_id="final_memory_dashboard",
            relation="exposes_subordinate_backend_status",
            read_only_relation=True,
            edge_ready=True,
        ),
        FinalMemoryMapEdge(
            edge_id="edge_sync_to_dashboard",
            from_node_id="memory_sync",
            to_node_id="final_memory_dashboard",
            relation="exposes_node_memory_consistency",
            read_only_relation=True,
            edge_ready=True,
        ),
        FinalMemoryMapEdge(
            edge_id="edge_artifact_to_dashboard",
            from_node_id="project_artifact_memory",
            to_node_id="final_memory_dashboard",
            relation="exposes_artifact_memory_visibility",
            read_only_relation=True,
            edge_ready=True,
        ),
        FinalMemoryMapEdge(
            edge_id="edge_regulatory_to_dashboard",
            from_node_id="enterprise_regulatory_memory",
            to_node_id="final_memory_dashboard",
            relation="exposes_regulatory_memory_visibility",
            read_only_relation=True,
            edge_ready=True,
        ),
    )

    return FinalMemoryMap(
        map_id="final_dashboard_memory_map_001",
        nodes=nodes,
        edges=edges,
        all_registered_modules_visible=True,
        all_storage_nodes_visible=True,
        all_retrieval_sources_visible=True,
        dashboard_read_only=True,
        canonical_write_allowed=False,
        runtime_mutation_allowed=False,
        map_ready=True,
    )
