from __future__ import annotations

UPDATE_RECOVERY_SERVER_PACKAGE_ID = "MAKSIMAR_SERVER_UPDATE_RECOVERY"
UPDATE_RECOVERY_SERVER_LAYER_ID = "UPDATE_RECOVERY_INFRA"
UPDATE_RECOVERY_SERVER_SURFACE_ROOT = "UPDATE_RECOVERY"
UPDATE_RECOVERY_SERVER_CONTAINER_READY = True
UPDATE_RECOVERY_SERVER_FACADE_WRAPPER_ONLY = True
UPDATE_RECOVERY_SERVER_CANONICAL_WRITE_ALLOWED = False
UPDATE_RECOVERY_SERVER_RUNTIME_BEHAVIOR_CHANGE_ALLOWED = False
UPDATE_RECOVERY_SERVER_DASHBOARD_EXECUTION_ALLOWED = False

__all__ = [
    "UPDATE_RECOVERY_SERVER_PACKAGE_ID",
    "UPDATE_RECOVERY_SERVER_LAYER_ID",
    "UPDATE_RECOVERY_SERVER_SURFACE_ROOT",
    "UPDATE_RECOVERY_SERVER_CONTAINER_READY",
    "UPDATE_RECOVERY_SERVER_FACADE_WRAPPER_ONLY",
    "UPDATE_RECOVERY_SERVER_CANONICAL_WRITE_ALLOWED",
    "UPDATE_RECOVERY_SERVER_RUNTIME_BEHAVIOR_CHANGE_ALLOWED",
    "UPDATE_RECOVERY_SERVER_DASHBOARD_EXECUTION_ALLOWED",
]
