from __future__ import annotations

DATA_PLANE_ADAPTERS_PACKAGE_ID = "MAKSIMAR_SERVER_DATA_PLANE_ADAPTERS"
DATA_PLANE_ADAPTERS_REFERENCE_ONLY = True
DATA_PLANE_ADAPTERS_DIRECT_EXECUTION_ALLOWED = False
DATA_PLANE_ADAPTERS_CANONICAL_WRITE_ALLOWED = False
DATA_PLANE_ADAPTERS_DASHBOARD_MUTATION_ALLOWED = False

__all__ = [
    "DATA_PLANE_ADAPTERS_PACKAGE_ID",
    "DATA_PLANE_ADAPTERS_REFERENCE_ONLY",
    "DATA_PLANE_ADAPTERS_DIRECT_EXECUTION_ALLOWED",
    "DATA_PLANE_ADAPTERS_CANONICAL_WRITE_ALLOWED",
    "DATA_PLANE_ADAPTERS_DASHBOARD_MUTATION_ALLOWED",
]
