#!/usr/bin/env bash
set -e

cd "$HOME/MAKSIMAR_PLATFORM/MAKSIMAR_CORE/contracts/dialogue"

cat > dialogue_state.v1.yaml <<'YAML'
contract_name: dialogue_state
schema_version: dialogue_state.v1
description: Canonical multi-turn dialogue state.

required:
  - dialogue_id
  - active_intent
  - active_context

fields:
  dialogue_id:
    type: string
    description: Unique dialogue session identifier.

  active_intent:
    type: string
    description: Currently active interpreted intent.

  active_context:
    type: string
    description: Current dialogue context label or context reference.

  unresolved_questions:
    type: array
    items:
      type: string
    description: Outstanding clarification points still unresolved.

  referenced_entities:
    type: array
    items:
      type: string
    description: Entity references currently active in the dialogue state.

validation_rules:
  - dialogue_id required
  - active_intent required
  - active_context required
  - unresolved_questions should be explicit even when empty
  - referenced_entities should be explicit even when empty

security_rules:
  - no execution authority
  - dialogue state must not embed hidden privileged commands
  - restricted references must be filtered by access policy
YAML

cat > dialogue_context.v1.yaml <<'YAML'
contract_name: dialogue_context
schema_version: dialogue_context.v1
description: Structured context package for dialogue manager.

required:
  - context_id
  - source_refs

fields:
  context_id:
    type: string
    description: Unique dialogue context package identifier.

  source_refs:
    type: array
    items:
      type: string
    description: Explicit source references used to assemble this context package.

  active_project_ref:
    type: string
    description: Reference to active project context when applicable.

  active_workflow_ref:
    type: string
    description: Reference to active workflow context when applicable.

  memory_snapshot_ref:
    type: string
    description: Reference to memory snapshot used to build the dialogue context.

validation_rules:
  - context_id required
  - source_refs required
  - source_refs must not be empty
  - active_project_ref and active_workflow_ref should be explicit when relevant

security_rules:
  - restricted context must be filtered by access policy
  - context packaging does not imply execution rights
  - source traceability must be preserved
YAML

cat > clarification_request.v1.yaml <<'YAML'
contract_name: clarification_request
schema_version: clarification_request.v1
description: Clarification turn request generated by dialogue manager.

required:
  - clarification_id
  - reason
  - options

fields:
  clarification_id:
    type: string
    description: Unique clarification request identifier.

  reason:
    type: string
    description: Reason why clarification is required.

  options:
    type: array
    items:
      type: string
    description: Explicit clarification options presented to the user or operator.

  linked_intent_ref:
    type: string
    description: Reference to the intent that triggered this clarification.

validation_rules:
  - clarification_id required
  - reason required
  - options required
  - options must not be empty
  - linked_intent_ref should be explicit when known

security_rules:
  - clarification must not conceal risk-critical ambiguity
  - clarification records do not authorize execution
  - unresolved dangerous ambiguity must remain blocking
YAML

cat > response_plan.v1.yaml <<'YAML'
contract_name: response_plan
schema_version: response_plan.v1
description: Planned response structure before final answer generation.

required:
  - response_plan_id
  - intent_ref
  - action_path

fields:
  response_plan_id:
    type: string
    description: Unique response plan identifier.

  intent_ref:
    type: string
    description: Reference to interpreted intent driving the response.

  action_path:
    type: array
    items:
      type: string
    description: Planned reasoning or tool path for forming the response.

  requires_clarification:
    type: boolean
    description: Whether clarification is required before safe completion.

  references:
    type: array
    items:
      type: string
    description: Supporting references used by the response plan.

validation_rules:
  - response_plan_id required
  - intent_ref required
  - action_path required
  - action_path must not be empty
  - requires_clarification should be explicit

security_rules:
  - response plan does not directly execute
  - response planning must not bypass approval or action policy
  - references must preserve access boundaries
YAML

echo "dialogue contracts restored successfully"
