import type { GraphProjectionRegistry } from "./graphProjectionTypes.js";

export const graphProjectionRegistry: GraphProjectionRegistry = {
  topology: {
    title: "Topology Graph",
    subtitle: "Canonical topology projection from graph adapter contracts.",
    inspectHint: "Inspect node roles, capabilities, and anchor relations.",
    nodes: [
      {
        id: "mobile_001",
        title: "mobile_001",
        subtitle: "mobile_node",
        semanticKind: "topology_anchor_node",
        position: { x: 320, y: 40 },
        fields: [
          { key: "role_type", value: "mobile_node" },
          { key: "operator_visible", value: "true" },
          { key: "security_root", value: "false" },
          { key: "heavy_execution_allowed", value: "false" },
          { key: "graph_projection_id", value: "mobile_001_graph_projection" },
        ],
      },
      {
        id: "dev_001",
        title: "dev_001",
        subtitle: "dev_node",
        semanticKind: "topology_execution_node",
        position: { x: 120, y: 220 },
        fields: [
          { key: "role_type", value: "dev_node" },
          { key: "operator_visible", value: "true" },
          { key: "security_root", value: "false" },
          { key: "heavy_execution_allowed", value: "true" },
          { key: "graph_projection_id", value: "dev_001_graph_projection" },
        ],
      },
      {
        id: "home_001",
        title: "home_001",
        subtitle: "home_node",
        semanticKind: "topology_execution_node",
        position: { x: 520, y: 220 },
        fields: [
          { key: "role_type", value: "home_node" },
          { key: "operator_visible", value: "true" },
          { key: "security_root", value: "false" },
          { key: "heavy_execution_allowed", value: "true" },
          { key: "graph_projection_id", value: "home_001_graph_projection" },
        ],
      },
    ],
    edges: [
      {
        id: "dev_001_to_mobile_001",
        source: "dev_001",
        target: "mobile_001",
        title: "dev → mobile",
        semanticKind: "topology_anchor_edge",
        fields: [
          { key: "source", value: "dev_001" },
          { key: "target", value: "mobile_001" },
          { key: "edge_class", value: "topology_anchor_edge" },
          { key: "projection_id", value: "dev_001_to_mobile_001_graph_edge" },
        ],
      },
      {
        id: "home_001_to_mobile_001",
        source: "home_001",
        target: "mobile_001",
        title: "home → mobile",
        semanticKind: "topology_anchor_edge",
        fields: [
          { key: "source", value: "home_001" },
          { key: "target", value: "mobile_001" },
          { key: "edge_class", value: "topology_anchor_edge" },
          { key: "projection_id", value: "home_001_to_mobile_001_graph_edge" },
        ],
      },
    ],
  },

  dependency: {
    title: "Dependency Graph",
    subtitle: "Canonical dependency projection from dependency graph adapter contracts.",
    inspectHint: "Inspect upstream/downstream module semantics and dependency class.",
    nodes: [
      {
        id: "control_plane",
        title: "control_plane",
        subtitle: "control domain",
        semanticKind: "dependency_node",
        position: { x: 60, y: 120 },
        fields: [
          { key: "domain", value: "control" },
          { key: "kind", value: "upstream_module" },
        ],
      },
      {
        id: "execution_control",
        title: "execution_control",
        subtitle: "execution domain",
        semanticKind: "dependency_node",
        position: { x: 320, y: 120 },
        fields: [
          { key: "domain", value: "execution" },
          { key: "kind", value: "execution_module" },
        ],
      },
      {
        id: "execution_observability",
        title: "execution_observability",
        subtitle: "observability domain",
        semanticKind: "dependency_node",
        position: { x: 620, y: 120 },
        fields: [
          { key: "domain", value: "observability" },
          { key: "kind", value: "projection_module" },
        ],
      },
      {
        id: "oob_dashboard",
        title: "oob_dashboard",
        subtitle: "dashboard domain",
        semanticKind: "dependency_node",
        position: { x: 940, y: 120 },
        fields: [
          { key: "domain", value: "dashboard" },
          { key: "kind", value: "read_only_surface" },
        ],
      },
    ],
    edges: [
      {
        id: "control_plane_to_execution_control",
        source: "control_plane",
        target: "execution_control",
        title: "control → execution",
        semanticKind: "execution_dependency",
        fields: [
          { key: "upstream", value: "control_plane" },
          { key: "downstream", value: "execution_control" },
          { key: "dependency_kind", value: "execution_dependency" },
        ],
      },
      {
        id: "execution_control_to_execution_observability",
        source: "execution_control",
        target: "execution_observability",
        title: "execution → observability",
        semanticKind: "execution_dependency",
        fields: [
          { key: "upstream", value: "execution_control" },
          { key: "downstream", value: "execution_observability" },
          { key: "dependency_kind", value: "execution_dependency" },
        ],
      },
      {
        id: "execution_observability_to_oob_dashboard",
        source: "execution_observability",
        target: "oob_dashboard",
        title: "observability → dashboard",
        semanticKind: "projection_dependency",
        fields: [
          { key: "upstream", value: "execution_observability" },
          { key: "downstream", value: "oob_dashboard" },
          { key: "dependency_kind", value: "projection_dependency" },
        ],
      },
    ],
  },

  dataflow: {
    title: "Dataflow Graph",
    subtitle: "Canonical dataflow projection from dataflow graph adapter contracts.",
    inspectHint: "Inspect data paths, observability projection, and cross-domain flow.",
    nodes: [
      {
        id: "control_plane",
        title: "control_plane",
        subtitle: "request source",
        semanticKind: "dataflow_node",
        position: { x: 60, y: 60 },
        fields: [
          { key: "flow_role", value: "request_source" },
          { key: "surface", value: "control" },
        ],
      },
      {
        id: "execution_control",
        title: "execution_control",
        subtitle: "dispatch hub",
        semanticKind: "dataflow_node",
        position: { x: 300, y: 60 },
        fields: [
          { key: "flow_role", value: "dispatch_hub" },
          { key: "surface", value: "execution" },
        ],
      },
      {
        id: "workers",
        title: "workers",
        subtitle: "worker fanout",
        semanticKind: "dataflow_node",
        position: { x: 540, y: 60 },
        fields: [
          { key: "flow_role", value: "worker_fanout" },
          { key: "surface", value: "execution" },
        ],
      },
      {
        id: "data_plane",
        title: "data_plane",
        subtitle: "artifact/data sink",
        semanticKind: "dataflow_node",
        position: { x: 780, y: 60 },
        fields: [
          { key: "flow_role", value: "data_sink" },
          { key: "surface", value: "data" },
        ],
      },
      {
        id: "execution_observability",
        title: "execution_observability",
        subtitle: "telemetry projection",
        semanticKind: "dataflow_node",
        position: { x: 300, y: 260 },
        fields: [
          { key: "flow_role", value: "telemetry_projection" },
          { key: "surface", value: "observability" },
        ],
      },
      {
        id: "oob_dashboard",
        title: "oob_dashboard",
        subtitle: "read-only dashboard sink",
        semanticKind: "dataflow_node",
        position: { x: 780, y: 260 },
        fields: [
          { key: "flow_role", value: "dashboard_sink" },
          { key: "surface", value: "dashboard" },
        ],
      },
    ],
    edges: [
      {
        id: "control_plane_to_execution_control",
        source: "control_plane",
        target: "execution_control",
        title: "control request",
        semanticKind: "control_to_execution",
        fields: [
          { key: "source_component", value: "control_plane" },
          { key: "target_component", value: "execution_control" },
          { key: "flow_class", value: "control_to_execution" },
        ],
      },
      {
        id: "execution_control_to_workers",
        source: "execution_control",
        target: "workers",
        title: "dispatch",
        semanticKind: "execution_to_workers",
        fields: [
          { key: "source_component", value: "execution_control" },
          { key: "target_component", value: "workers" },
          { key: "flow_class", value: "execution_to_workers" },
        ],
      },
      {
        id: "workers_to_data_plane",
        source: "workers",
        target: "data_plane",
        title: "artifact/data output",
        semanticKind: "workers_to_data_plane",
        fields: [
          { key: "source_component", value: "workers" },
          { key: "target_component", value: "data_plane" },
          { key: "flow_class", value: "workers_to_data_plane" },
        ],
      },
      {
        id: "execution_observability_to_oob_dashboard",
        source: "execution_observability",
        target: "oob_dashboard",
        title: "dashboard projection",
        semanticKind: "observability_projection",
        fields: [
          { key: "source_component", value: "execution_observability" },
          { key: "target_component", value: "oob_dashboard" },
          { key: "flow_class", value: "observability_projection" },
        ],
      },
      {
        id: "control_plane_to_execution_observability",
        source: "control_plane",
        target: "execution_observability",
        title: "control telemetry",
        semanticKind: "control_to_observability",
        fields: [
          { key: "source_component", value: "control_plane" },
          { key: "target_component", value: "execution_observability" },
          { key: "flow_class", value: "control_to_observability" },
        ],
      },
    ],
  },

  modules: {
    title: "Module Graph",
    subtitle: "Canonical module surface / navigation / audit preview.",
    inspectHint: "Inspect module role, workspace, and projection continuity.",
    nodes: [
      {
        id: "module_manifest_001",
        title: "module_manifest_001",
        subtitle: "foundation_monitoring_module",
        semanticKind: "module_surface",
        position: { x: 120, y: 80 },
        fields: [
          { key: "module_role", value: "base_family_module" },
          { key: "surface_id", value: "foundation_monitoring_module_surface" },
          { key: "navigation_id", value: "foundation_monitoring_module_nav" },
          { key: "workspace_id", value: "workspace_foundation_monitoring" },
          { key: "registry_audit_id", value: "module_registry_audit_001" },
        ],
      },
      {
        id: "module_manifest_002",
        title: "module_manifest_002",
        subtitle: "operator_interaction_module",
        semanticKind: "module_surface",
        position: { x: 500, y: 80 },
        fields: [
          { key: "module_role", value: "operator_module" },
          { key: "surface_id", value: "operator_interaction_module_surface" },
          { key: "navigation_id", value: "operator_interaction_module_nav" },
          { key: "workspace_id", value: "workspace_operator_interaction" },
          { key: "registry_audit_id", value: "module_registry_audit_002" },
        ],
      },
      {
        id: "module_manifest_003",
        title: "module_manifest_003",
        subtitle: "optional_product_module",
        semanticKind: "module_surface",
        position: { x: 880, y: 80 },
        fields: [
          { key: "module_role", value: "optional_product_module" },
          { key: "surface_id", value: "optional_product_module_surface" },
          { key: "navigation_id", value: "optional_product_module_nav" },
          { key: "workspace_id", value: "workspace_operator_interaction" },
          { key: "registry_audit_id", value: "module_registry_audit_003" },
        ],
      },
    ],
    edges: [
      {
        id: "module_001_surface",
        source: "module_manifest_001",
        target: "module_manifest_002",
        title: "surface continuity",
        semanticKind: "surface_navigation_continuity",
        fields: [
          { key: "from", value: "module_manifest_001" },
          { key: "to", value: "module_manifest_002" },
          { key: "meaning", value: "surface/navigation continuity" },
        ],
      },
      {
        id: "module_002_surface",
        source: "module_manifest_002",
        target: "module_manifest_003",
        title: "surface continuity",
        semanticKind: "surface_navigation_continuity",
        fields: [
          { key: "from", value: "module_manifest_002" },
          { key: "to", value: "module_manifest_003" },
          { key: "meaning", value: "surface/navigation continuity" },
        ],
      },
      {
        id: "module_003_audit",
        source: "module_manifest_001",
        target: "module_manifest_003",
        title: "audit visibility",
        semanticKind: "audit_visibility_relation",
        fields: [
          { key: "from", value: "module_manifest_001" },
          { key: "to", value: "module_manifest_003" },
          { key: "meaning", value: "audit visibility" },
        ],
      },
    ],
  },

  guard_chain: {
    title: "Guard Chain Graph",
    subtitle: "Foundation guard-chain truth ordering from foundation_guard_chain_truth_view.",
    inspectHint: "Inspect the ordered safety chain: runtime, guard, core guard, kernel watchdog.",
    nodes: [
      {
        id: "guard_runtime",
        title: "Runtime Core",
        subtitle: "runtime",
        semanticKind: "guard_chain_node",
        position: { x: 80, y: 140 },
        fields: [
          { key: "truth_scope", value: "runtime" },
          { key: "display_title", value: "Runtime Core" },
          { key: "chain_order_index", value: "1" },
          { key: "read_only", value: "true" },
        ],
      },
      {
        id: "guard_stop_gate",
        title: "Stop-Gate Watcher",
        subtitle: "guard",
        semanticKind: "guard_chain_node",
        position: { x: 340, y: 140 },
        fields: [
          { key: "truth_scope", value: "guard" },
          { key: "display_title", value: "Stop-Gate Watcher" },
          { key: "chain_order_index", value: "2" },
          { key: "read_only", value: "true" },
        ],
      },
      {
        id: "guard_core_guard",
        title: "Core Guard",
        subtitle: "core_guard",
        semanticKind: "guard_chain_node",
        position: { x: 620, y: 140 },
        fields: [
          { key: "truth_scope", value: "core_guard" },
          { key: "display_title", value: "Core Guard" },
          { key: "chain_order_index", value: "3" },
          { key: "read_only", value: "true" },
        ],
      },
      {
        id: "guard_kernel_watchdog",
        title: "Kernel Watchdog",
        subtitle: "kernel_guard",
        semanticKind: "guard_chain_node",
        position: { x: 920, y: 140 },
        fields: [
          { key: "truth_scope", value: "kernel_guard" },
          { key: "display_title", value: "Kernel Watchdog" },
          { key: "chain_order_index", value: "4" },
          { key: "read_only", value: "true" },
        ],
      },
    ],
    edges: [
      {
        id: "guard_runtime_to_stop_gate",
        source: "guard_runtime",
        target: "guard_stop_gate",
        title: "runtime → stop-gate",
        semanticKind: "guard_chain_relation",
        fields: [
          { key: "from_scope", value: "runtime" },
          { key: "to_scope", value: "guard" },
          { key: "relation_kind", value: "guard_chain_step" },
        ],
      },
      {
        id: "guard_stop_gate_to_core_guard",
        source: "guard_stop_gate",
        target: "guard_core_guard",
        title: "stop-gate → core guard",
        semanticKind: "guard_chain_relation",
        fields: [
          { key: "from_scope", value: "guard" },
          { key: "to_scope", value: "core_guard" },
          { key: "relation_kind", value: "guard_chain_step" },
        ],
      },
      {
        id: "guard_core_guard_to_kernel_watchdog",
        source: "guard_core_guard",
        target: "guard_kernel_watchdog",
        title: "core guard → kernel watchdog",
        semanticKind: "guard_chain_relation",
        fields: [
          { key: "from_scope", value: "core_guard" },
          { key: "to_scope", value: "kernel_guard" },
          { key: "relation_kind", value: "guard_chain_step" },
        ],
      },
    ],
  },

  truth_consistency: {
    title: "Truth Consistency Graph",
    subtitle: "Foundation truth consistency view with panel bindings.",
    inspectHint: "Inspect truth scope, panel binding, derived status fields, and truth-source coverage.",
    nodes: [
      {
        id: "truth_runtime",
        title: "Runtime Core",
        subtitle: "panel_foundation_runtime_status_001",
        semanticKind: "truth_consistency_node",
        position: { x: 80, y: 120 },
        fields: [
          { key: "truth_scope", value: "runtime" },
          { key: "display_title", value: "Runtime Core" },
          { key: "panel_id", value: "panel_foundation_runtime_status_001" },
          { key: "view_id", value: "foundation_truth_consistency_view_001" },
          { key: "read_only", value: "true" },
        ],
      },
      {
        id: "truth_guard",
        title: "Stop-Gate Watcher",
        subtitle: "panel_foundation_guard_status_001",
        semanticKind: "truth_consistency_node",
        position: { x: 340, y: 120 },
        fields: [
          { key: "truth_scope", value: "guard" },
          { key: "display_title", value: "Stop-Gate Watcher" },
          { key: "panel_id", value: "panel_foundation_guard_status_001" },
          { key: "view_id", value: "foundation_truth_consistency_view_001" },
          { key: "read_only", value: "true" },
        ],
      },
      {
        id: "truth_core_guard",
        title: "Core Guard",
        subtitle: "panel_foundation_core_guard_status_001",
        semanticKind: "truth_consistency_node",
        position: { x: 620, y: 120 },
        fields: [
          { key: "truth_scope", value: "core_guard" },
          { key: "display_title", value: "Core Guard" },
          { key: "panel_id", value: "panel_foundation_core_guard_status_001" },
          { key: "view_id", value: "foundation_truth_consistency_view_001" },
          { key: "read_only", value: "true" },
        ],
      },
      {
        id: "truth_kernel_guard",
        title: "Kernel Watchdog",
        subtitle: "panel_foundation_kernel_guard_status_001",
        semanticKind: "truth_consistency_node",
        position: { x: 920, y: 120 },
        fields: [
          { key: "truth_scope", value: "kernel_guard" },
          { key: "display_title", value: "Kernel Watchdog" },
          { key: "panel_id", value: "panel_foundation_kernel_guard_status_001" },
          { key: "view_id", value: "foundation_truth_consistency_view_001" },
          { key: "read_only", value: "true" },
        ],
      },
    ],
    edges: [
      {
        id: "truth_runtime_to_guard",
        source: "truth_runtime",
        target: "truth_guard",
        title: "truth scope sequence",
        semanticKind: "truth_consistency_relation",
        fields: [
          { key: "from_scope", value: "runtime" },
          { key: "to_scope", value: "guard" },
          { key: "relation_kind", value: "truth_scope_sequence" },
        ],
      },
      {
        id: "truth_guard_to_core_guard",
        source: "truth_guard",
        target: "truth_core_guard",
        title: "truth scope sequence",
        semanticKind: "truth_consistency_relation",
        fields: [
          { key: "from_scope", value: "guard" },
          { key: "to_scope", value: "core_guard" },
          { key: "relation_kind", value: "truth_scope_sequence" },
        ],
      },
      {
        id: "truth_core_guard_to_kernel_guard",
        source: "truth_core_guard",
        target: "truth_kernel_guard",
        title: "truth scope sequence",
        semanticKind: "truth_consistency_relation",
        fields: [
          { key: "from_scope", value: "core_guard" },
          { key: "to_scope", value: "kernel_guard" },
          { key: "relation_kind", value: "truth_scope_sequence" },
        ],
      },
    ],
  },

  workspace: {
    title: "Workspace Graph",
    subtitle: "Workspace displays and panel placements from workspace_contract.",
    inspectHint: "Inspect display roles, workspace IDs, zones, and slot placements.",
    nodes: [
      {
        id: "display_primary_operator",
        title: "display_primary_operator",
        subtitle: "primary_operator",
        semanticKind: "workspace_display_node",
        position: { x: 160, y: 40 },
        fields: [
          { key: "display_id", value: "0" },
          { key: "display_role", value: "primary_operator" },
          { key: "operator_visible", value: "true" },
        ],
      },
      {
        id: "display_secondary_diagnostics",
        title: "display_secondary_diagnostics",
        subtitle: "secondary_diagnostics",
        semanticKind: "workspace_display_node",
        position: { x: 520, y: 40 },
        fields: [
          { key: "display_id", value: "1" },
          { key: "display_role", value: "secondary_diagnostics" },
          { key: "operator_visible", value: "true" },
        ],
      },
      {
        id: "display_tertiary_expansion",
        title: "display_tertiary_expansion",
        subtitle: "tertiary_expansion",
        semanticKind: "workspace_display_node",
        position: { x: 900, y: 40 },
        fields: [
          { key: "display_id", value: "2" },
          { key: "display_role", value: "tertiary_expansion" },
          { key: "operator_visible", value: "true" },
        ],
      },
      {
        id: "workspace_placement_001",
        title: "panel_consistency",
        subtitle: "workspace_foundation_monitoring",
        semanticKind: "workspace_panel_node",
        position: { x: 420, y: 220 },
        fields: [
          { key: "placement_id", value: "workspace_placement_001" },
          { key: "panel_id", value: "panel_consistency" },
          { key: "zone_id", value: "zone_main" },
          { key: "slot_id", value: "slot_001" },
        ],
      },
      {
        id: "workspace_placement_002",
        title: "panel_snapshot",
        subtitle: "workspace_foundation_monitoring",
        semanticKind: "workspace_panel_node",
        position: { x: 520, y: 220 },
        fields: [
          { key: "placement_id", value: "workspace_placement_002" },
          { key: "panel_id", value: "panel_snapshot" },
          { key: "zone_id", value: "zone_main" },
          { key: "slot_id", value: "slot_002" },
        ],
      },
      {
        id: "workspace_placement_003",
        title: "panel_incident",
        subtitle: "workspace_foundation_monitoring",
        semanticKind: "workspace_panel_node",
        position: { x: 620, y: 220 },
        fields: [
          { key: "placement_id", value: "workspace_placement_003" },
          { key: "panel_id", value: "panel_incident" },
          { key: "zone_id", value: "zone_main" },
          { key: "slot_id", value: "slot_003" },
        ],
      },
      {
        id: "workspace_placement_004",
        title: "panel_diagnostics",
        subtitle: "workspace_expansion_observability",
        semanticKind: "workspace_panel_node",
        position: { x: 900, y: 220 },
        fields: [
          { key: "placement_id", value: "workspace_placement_004" },
          { key: "panel_id", value: "panel_diagnostics" },
          { key: "zone_id", value: "zone_main" },
          { key: "slot_id", value: "slot_001" },
        ],
      },
      {
        id: "workspace_placement_005",
        title: "panel_chat",
        subtitle: "workspace_operator_main",
        semanticKind: "workspace_panel_node",
        position: { x: 60, y: 220 },
        fields: [
          { key: "placement_id", value: "workspace_placement_005" },
          { key: "panel_id", value: "panel_chat" },
          { key: "zone_id", value: "zone_main" },
          { key: "slot_id", value: "slot_001" },
        ],
      },
      {
        id: "workspace_placement_006",
        title: "panel_settings",
        subtitle: "workspace_operator_main",
        semanticKind: "workspace_panel_node",
        position: { x: 160, y: 320 },
        fields: [
          { key: "placement_id", value: "workspace_placement_006" },
          { key: "panel_id", value: "panel_settings" },
          { key: "zone_id", value: "zone_sidebar" },
          { key: "slot_id", value: "slot_001" },
        ],
      },
      {
        id: "workspace_placement_007",
        title: "panel_gesture_control",
        subtitle: "workspace_operator_main",
        semanticKind: "workspace_panel_node",
        position: { x: 260, y: 320 },
        fields: [
          { key: "placement_id", value: "workspace_placement_007" },
          { key: "panel_id", value: "panel_gesture_control" },
          { key: "zone_id", value: "zone_sidebar" },
          { key: "slot_id", value: "slot_002" },
        ],
      },
    ],
    edges: [
      {
        id: "workspace_placement_001_to_display",
        source: "workspace_placement_001",
        target: "display_secondary_diagnostics",
        title: "placement → display",
        semanticKind: "workspace_placement_relation",
        fields: [
          { key: "display_target_id", value: "display_secondary_diagnostics" },
          { key: "workspace_id", value: "workspace_foundation_monitoring" },
        ],
      },
      {
        id: "workspace_placement_002_to_display",
        source: "workspace_placement_002",
        target: "display_secondary_diagnostics",
        title: "placement → display",
        semanticKind: "workspace_placement_relation",
        fields: [
          { key: "display_target_id", value: "display_secondary_diagnostics" },
          { key: "workspace_id", value: "workspace_foundation_monitoring" },
        ],
      },
      {
        id: "workspace_placement_003_to_display",
        source: "workspace_placement_003",
        target: "display_secondary_diagnostics",
        title: "placement → display",
        semanticKind: "workspace_placement_relation",
        fields: [
          { key: "display_target_id", value: "display_secondary_diagnostics" },
          { key: "workspace_id", value: "workspace_foundation_monitoring" },
        ],
      },
      {
        id: "workspace_placement_004_to_display",
        source: "workspace_placement_004",
        target: "display_tertiary_expansion",
        title: "placement → display",
        semanticKind: "workspace_placement_relation",
        fields: [
          { key: "display_target_id", value: "display_tertiary_expansion" },
          { key: "workspace_id", value: "workspace_expansion_observability" },
        ],
      },
      {
        id: "workspace_placement_005_to_display",
        source: "workspace_placement_005",
        target: "display_primary_operator",
        title: "placement → display",
        semanticKind: "workspace_placement_relation",
        fields: [
          { key: "display_target_id", value: "display_primary_operator" },
          { key: "workspace_id", value: "workspace_operator_main" },
        ],
      },
      {
        id: "workspace_placement_006_to_display",
        source: "workspace_placement_006",
        target: "display_primary_operator",
        title: "placement → display",
        semanticKind: "workspace_placement_relation",
        fields: [
          { key: "display_target_id", value: "display_primary_operator" },
          { key: "workspace_id", value: "workspace_operator_main" },
        ],
      },
      {
        id: "workspace_placement_007_to_display",
        source: "workspace_placement_007",
        target: "display_primary_operator",
        title: "placement → display",
        semanticKind: "workspace_placement_relation",
        fields: [
          { key: "display_target_id", value: "display_primary_operator" },
          { key: "workspace_id", value: "workspace_operator_main" },
        ],
      },
    ],
  },

  displays: {
    title: "Display Assignment Graph",
    subtitle: "Display assignment registry expansion from display assignment contracts.",
    inspectHint: "Inspect display targets, assigned surfaces, replaceability, and assignment state.",
    nodes: [
      {
        id: "display_foundation_primary",
        title: "display_foundation_primary",
        subtitle: "foundation primary target",
        semanticKind: "display_target_node",
        position: { x: 120, y: 60 },
        fields: [
          { key: "display_target_id", value: "display_foundation_primary" },
          { key: "operator_visible", value: "true" },
        ],
      },
      {
        id: "display_foundation_secondary",
        title: "display_foundation_secondary",
        subtitle: "foundation secondary target",
        semanticKind: "display_target_node",
        position: { x: 520, y: 60 },
        fields: [
          { key: "display_target_id", value: "display_foundation_secondary" },
          { key: "operator_visible", value: "true" },
        ],
      },
      {
        id: "display_operator_interaction",
        title: "display_operator_interaction",
        subtitle: "operator interaction target",
        semanticKind: "display_target_node",
        position: { x: 920, y: 60 },
        fields: [
          { key: "display_target_id", value: "display_operator_interaction" },
          { key: "operator_visible", value: "true" },
        ],
      },
      {
        id: "workspace_foundation_monitoring_surface",
        title: "workspace_foundation_monitoring_surface",
        subtitle: "foundation workspace surface",
        semanticKind: "display_surface_node",
        position: { x: 120, y: 240 },
        fields: [
          { key: "panel_or_surface_id", value: "workspace_foundation_monitoring_surface" },
          { key: "assignment_role", value: "foundation_primary_surface" },
        ],
      },
      {
        id: "panel_logs_surface",
        title: "panel_logs_surface",
        subtitle: "logs panel surface",
        semanticKind: "display_surface_node",
        position: { x: 420, y: 240 },
        fields: [
          { key: "panel_or_surface_id", value: "panel_logs_surface" },
          { key: "assignment_role", value: "foundation_secondary_surface" },
        ],
      },
      {
        id: "panel_topology_surface",
        title: "panel_topology_surface",
        subtitle: "topology panel surface",
        semanticKind: "display_surface_node",
        position: { x: 620, y: 240 },
        fields: [
          { key: "panel_or_surface_id", value: "panel_topology_surface" },
          { key: "assignment_role", value: "foundation_secondary_surface" },
        ],
      },
      {
        id: "workspace_operator_interaction_surface",
        title: "workspace_operator_interaction_surface",
        subtitle: "operator interaction workspace surface",
        semanticKind: "display_surface_node",
        position: { x: 920, y: 240 },
        fields: [
          { key: "panel_or_surface_id", value: "workspace_operator_interaction_surface" },
          { key: "assignment_role", value: "operator_interaction_surface" },
        ],
      },
    ],
    edges: [
      {
        id: "display_assignment_001",
        source: "workspace_foundation_monitoring_surface",
        target: "display_foundation_primary",
        title: "foundation primary assignment",
        semanticKind: "display_assignment_relation",
        fields: [
          { key: "assignment_id", value: "display_assignment_001" },
          { key: "assignment_state", value: "display_assignment_active" },
          { key: "replaceable", value: "false" },
        ],
      },
      {
        id: "display_assignment_002",
        source: "panel_logs_surface",
        target: "display_foundation_secondary",
        title: "logs panel assignment",
        semanticKind: "display_assignment_relation",
        fields: [
          { key: "assignment_id", value: "display_assignment_002" },
          { key: "assignment_state", value: "display_assignment_active" },
          { key: "replaceable", value: "true" },
        ],
      },
      {
        id: "display_assignment_003",
        source: "panel_topology_surface",
        target: "display_foundation_secondary",
        title: "topology panel assignment",
        semanticKind: "display_assignment_relation",
        fields: [
          { key: "assignment_id", value: "display_assignment_003" },
          { key: "assignment_state", value: "display_assignment_active" },
          { key: "replaceable", value: "true" },
        ],
      },
      {
        id: "display_assignment_004",
        source: "workspace_operator_interaction_surface",
        target: "display_operator_interaction",
        title: "operator interaction assignment",
        semanticKind: "display_assignment_relation",
        fields: [
          { key: "assignment_id", value: "display_assignment_004" },
          { key: "assignment_state", value: "display_assignment_active" },
          { key: "replaceable", value: "true" },
        ],
      },
    ],
  },
};
