from __future__ import annotations

SECURITY_LAYER_SERVER_SURFACE_ID = "MAKSIMAR_SERVER_SECURITY_LAYER"
SECURITY_LAYER_SERVER_BATCH_ID = "PHASE_1_BATCH_1_1"
SECURITY_LAYER_SERVER_RUNTIME_ENABLED = False
SECURITY_LAYER_SERVER_CONTAINER_ENABLED = False
SECURITY_LAYER_SERVER_DIRECT_EXECUTION_ALLOWED = False
SECURITY_LAYER_SERVER_DASHBOARD_MUTATION_ALLOWED = False

__all__ = [
    "SECURITY_LAYER_SERVER_SURFACE_ID",
    "SECURITY_LAYER_SERVER_BATCH_ID",
    "SECURITY_LAYER_SERVER_RUNTIME_ENABLED",
    "SECURITY_LAYER_SERVER_CONTAINER_ENABLED",
    "SECURITY_LAYER_SERVER_DIRECT_EXECUTION_ALLOWED",
    "SECURITY_LAYER_SERVER_DASHBOARD_MUTATION_ALLOWED",
]
