import type { DashboardSkeletonSurface } from "./types.js";

export const DASHBOARD_SKELETON_SURFACE_TAXONOMY: readonly DashboardSkeletonSurface[] = [
  {
    surfaceId: "operator_home",
    title: "Main Operator Dashboard",
    domain: "operator_core",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "home",
    renderMode: "graph_view",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Captain bridge shell: chat, approvals, navigation, active dashboard surface.",
  },
  {
    surfaceId: "foundation_unified_dashboard",
    title: "Foundation Unified Dashboard",
    domain: "foundation_truth",
    moduleKind: "system_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "foundation",
    renderMode: "status_panel",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Read-only foundation truth dashboard for runtime/core/guard health.",
  },
  {
    surfaceId: "foundation_incident_dashboard",
    title: "Foundation Incident Dashboard",
    domain: "incident_diagnostics",
    moduleKind: "system_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "incidents",
    renderMode: "timeline_panel",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Incident, failure localization and root-cause visibility surface.",
  },
  {
    surfaceId: "foundation_diagnostics_correlation",
    title: "Diagnostics Correlation",
    domain: "incident_diagnostics",
    moduleKind: "system_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "incidents",
    renderMode: "dependency_map_view",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Correlation surface for diagnostics, cascade paths and failure relationships.",
  },
  {
    surfaceId: "topology_graph",
    title: "Topology Graph",
    domain: "visual_graphs",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "graphs",
    renderMode: "graph_view",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Topology graph for nodes, devices, services and runtime graph surfaces.",
  },
  {
    surfaceId: "dependency_graph",
    title: "Dependency Graph",
    domain: "visual_graphs",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "graphs",
    renderMode: "dependency_map_view",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Reserved dependency graph for code/module/cube relationship visibility.",
  },
  {
    surfaceId: "dataflow_graph",
    title: "Dataflow Graph",
    domain: "visual_graphs",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "graphs",
    renderMode: "graph_view",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Reserved dataflow graph for pipeline and artifact movement visibility.",
  },
  {
    surfaceId: "displays_graph",
    title: "Displays Graph",
    domain: "visual_graphs",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "graphs",
    renderMode: "device_map_view",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Reserved display topology graph for monitor/tablet/mobile output routing.",
  },

  {
    surfaceId: "modules_graph",
    title: "Modules Graph",
    domain: "visual_graphs",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "graphs",
    renderMode: "graph_view",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Canonical module/cube graph for module surfaces, navigation and audit visibility.",
  },
  {
    surfaceId: "guard_chain_graph",
    title: "Guard Chain Graph",
    domain: "visual_graphs",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "graphs",
    renderMode: "graph_view",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Canonical guard-chain graph for STOP-GATE, safety perimeter and policy visibility.",
  },
  {
    surfaceId: "truth_consistency_graph",
    title: "Truth Consistency Graph",
    domain: "visual_graphs",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "graphs",
    renderMode: "graph_view",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Canonical truth-consistency graph for source-of-truth alignment and drift visibility.",
  },
  {
    surfaceId: "workspace_graph",
    title: "Workspace Graph",
    domain: "visual_graphs",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "graphs",
    renderMode: "graph_view",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Canonical workspace/display graph for operator workspace and display placement visibility.",
  },

  {
    surfaceId: "node_resources_chart",
    title: "Node Resources",
    domain: "telemetry_charts",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "telemetry",
    renderMode: "chart_view",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "CPU, RAM, GPU, thermal and runtime resource telemetry.",
  },
  {
    surfaceId: "security_telemetry_chart",
    title: "Security Telemetry",
    domain: "telemetry_charts",
    moduleKind: "system_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "telemetry",
    renderMode: "chart_view",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Security, guard-chain, policy and violation telemetry.",
  },
  {
    surfaceId: "multi_series_summary_chart",
    title: "Multi-Series Summary",
    domain: "telemetry_charts",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "telemetry",
    renderMode: "chart_view",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Multi-series summary chart for cross-domain analytics.",
  },
  {
    surfaceId: "action_queue_panel",
    title: "Action Queue",
    domain: "operator_interaction",
    moduleKind: "core_dashboard",
    targetZone: "right_context",
    buttonGroup: "interaction",
    renderMode: "timeline_panel",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Operator-facing action queue surface.",
  },
  {
    surfaceId: "approval_queue_panel",
    title: "Approval Queue",
    domain: "operator_interaction",
    moduleKind: "core_dashboard",
    targetZone: "right_context",
    buttonGroup: "interaction",
    renderMode: "timeline_panel",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Human approval queue for guarded actions and critical proposals.",
  },
  {
    surfaceId: "audit_timeline_panel",
    title: "Audit Timeline",
    domain: "operator_interaction",
    moduleKind: "system_dashboard",
    targetZone: "right_context",
    buttonGroup: "interaction",
    renderMode: "timeline_panel",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Immutable audit timeline surface for operator/JARVIS actions.",
  },
  {
    surfaceId: "memory_control_dashboard",
    title: "Memory Control Dashboard",
    domain: "memory_governance",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "memory",
    renderMode: "memory_map_view",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Control dashboard for memory layers, domains, folders, sequence and bindings.",
  },
  {
    surfaceId: "memory_layers_map",
    title: "Memory Layers Map",
    domain: "memory_governance",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "memory",
    renderMode: "memory_map_view",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Memory layer topology: constitutional, regulatory, technical, tenant, project and chat-history memory.",
  },
  {
    surfaceId: "memory_folder_sequence",
    title: "Memory Folder Sequence",
    domain: "memory_governance",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "memory",
    renderMode: "table_panel",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Ordered folder/domain sequence surface for multi-layer memory control.",
  },
  {
    surfaceId: "memory_governance_policy",
    title: "Memory Governance Policy",
    domain: "memory_governance",
    moduleKind: "system_dashboard",
    targetZone: "right_context",
    buttonGroup: "memory",
    renderMode: "table_panel",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Read/write rules, policy, source-of-truth and governance visibility for memory.",
  },
  {
    surfaceId: "embedded_jarvis_chat_surface",
    title: "Embedded JARVIS Chat",
    domain: "project_context",
    moduleKind: "core_dashboard",
    targetZone: "top_communication",
    buttonGroup: "project_context",
    renderMode: "chat_surface",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Top communication layer for JARVIS chat and operator messages.",
  },
  {
    surfaceId: "project_context_surface",
    title: "Project Context Surface",
    domain: "project_context",
    moduleKind: "core_dashboard",
    targetZone: "right_context",
    buttonGroup: "project_context",
    renderMode: "table_panel",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Project context, file/rule awareness and current reasoning context visibility.",
  },
  {
    surfaceId: "server_runtime",
    title: "Server Runtime",
    domain: "server_runtime",
    moduleKind: "core_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "server",
    renderMode: "chart_view",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Server runtime resource and service health dashboard surface.",
  },
  {
    surfaceId: "network_security",
    title: "Network / Security",
    domain: "network_security",
    moduleKind: "system_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "security",
    renderMode: "graph_view",
    status: "implemented",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Network, security boundary, guard chain and trust-zone surface.",
  },
  {
    surfaceId: "base_family_dashboard",
    title: "Base Family Dashboard",
    domain: "family_presence",
    moduleKind: "client_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "family",
    renderMode: "status_panel",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Family hub, presence, household assistant and child-monitoring surface.",
  },
  {
    surfaceId: "mobile_companion_android",
    title: "Android Companion",
    domain: "mobile_companion",
    moduleKind: "client_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "mobile",
    renderMode: "device_map_view",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Android client companion surface. Separate from Family dashboard domain.",
  },
  {
    surfaceId: "mobile_companion_ios",
    title: "iOS Companion",
    domain: "mobile_companion",
    moduleKind: "client_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "mobile",
    renderMode: "device_map_view",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "iOS client companion surface. Separate from Family dashboard domain.",
  },
  {
    surfaceId: "smart_home",
    title: "Smart Home",
    domain: "smart_home",
    moduleKind: "client_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "smart_home",
    renderMode: "status_panel",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Smart home control/status dashboard surface.",
  },
  {
    surfaceId: "simulation_dashboards_pack",
    title: "Simulation Dashboards Pack",
    domain: "simulation_sandbox",
    moduleKind: "cube_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "simulation",
    renderMode: "simulation_scene_adapter",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: true,
    description: "Simulation dashboard pack for sandbox, test and digital experiment surfaces.",
  },
  {
    surfaceId: "physics_digital_twin_dashboards",
    title: "Physics / Digital Twin",
    domain: "physics_digital_twin",
    moduleKind: "cube_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "simulation",
    renderMode: "simulation_scene_adapter",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: true,
    description: "3D/digital twin surface for future physical systems and simulated machines.",
  },
  {
    surfaceId: "industrial_robotics_dashboards",
    title: "Industrial Robotics",
    domain: "robotics_industrial",
    moduleKind: "cube_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "robotics",
    renderMode: "simulation_scene_adapter",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: true,
    description: "Industrial robotics, PLC/SCADA, machine telemetry and safety-zone surface.",
  },
  {
    surfaceId: "robotics_control",
    title: "Robotics Control",
    domain: "robotics_industrial",
    moduleKind: "cube_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "robotics",
    renderMode: "simulation_scene_adapter",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: true,
    description: "Robot, robodog and telemetry visualization surface.",
  },
  {
    surfaceId: "engineering_3d_cad_cam",
    title: "3D / CAD / CAM",
    domain: "engineering_3d_cad_cam",
    moduleKind: "cube_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "engineering",
    renderMode: "three_d_scene_adapter",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: true,
    description: "General 3D renderer surface for dashboard data, CAD/CAM, geometry and model visualization.",
  },
  {
    surfaceId: "content_growth_media",
    title: "Content / Media",
    domain: "content_growth_media",
    moduleKind: "cube_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "media",
    renderMode: "timeline_panel",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: false,
    adapterBoundaryRequired: false,
    description: "Content engine, publishing, media and growth dashboard surface.",
  },
  {
    surfaceId: "business_finance",
    title: "Business / Finance",
    domain: "business_finance",
    moduleKind: "client_dashboard",
    targetZone: "center_viewport",
    buttonGroup: "business",
    renderMode: "chart_view",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "Billing, packages, contracts, customer delivery and finance surface.",
  },
  {
    surfaceId: "system_settings",
    title: "System Settings",
    domain: "system_settings",
    moduleKind: "system_dashboard",
    targetZone: "right_context",
    buttonGroup: "settings",
    renderMode: "table_panel",
    status: "reserved",
    clientSelectable: true,
    requiresApproval: true,
    adapterBoundaryRequired: false,
    description: "System settings, configuration and policy visibility surface.",
  },
];
