import type { DashboardRendererAdapterContract } from "./types.js";

export const DASHBOARD_RENDERER_ADAPTER_REGISTRY: readonly DashboardRendererAdapterContract[] = [
  {
    adapterId: "react_flow_graph_renderer",
    title: "React Flow Graph Renderer",
    adapterKind: "react_flow_graph_renderer",
    supportedRenderModes: ["graph_view", "dependency_map_view", "device_map_view"],
    supportedTargetZones: ["center_viewport"],
    centerViewportCompatible: true,
    appTsxHardcodingAllowed: false,
    directEngineBindingAllowed: false,
    bindingPolicy: "adapter_boundary_only",
    safetyMode: "read_only_visualization",
    description: "Graph renderer adapter for topology, dependencies, dataflow and display maps.",
  },
  {
    adapterId: "echarts_chart_renderer",
    title: "ECharts Chart Renderer",
    adapterKind: "echarts_chart_renderer",
    supportedRenderModes: ["chart_view"],
    supportedTargetZones: ["center_viewport"],
    centerViewportCompatible: true,
    appTsxHardcodingAllowed: false,
    directEngineBindingAllowed: false,
    bindingPolicy: "adapter_boundary_only",
    safetyMode: "read_only_visualization",
    description: "Chart renderer adapter for telemetry and summary chart surfaces.",
  },
  {
    adapterId: "panel_renderer",
    title: "Panel Renderer",
    adapterKind: "panel_renderer",
    supportedRenderModes: ["status_panel", "table_panel", "timeline_panel"],
    supportedTargetZones: ["center_viewport", "right_context", "footer_status"],
    centerViewportCompatible: true,
    appTsxHardcodingAllowed: false,
    directEngineBindingAllowed: false,
    bindingPolicy: "adapter_boundary_only",
    safetyMode: "read_only_visualization",
    description: "Generic panel renderer for status, table and timeline dashboard surfaces.",
  },
  {
    adapterId: "chat_surface_renderer",
    title: "Chat Surface Renderer",
    adapterKind: "chat_surface_renderer",
    supportedRenderModes: ["chat_surface"],
    supportedTargetZones: ["top_communication", "right_context"],
    centerViewportCompatible: false,
    appTsxHardcodingAllowed: false,
    directEngineBindingAllowed: false,
    bindingPolicy: "adapter_boundary_only",
    safetyMode: "guarded_interactive_preview",
    description: "Communication surface renderer for JARVIS chat and project context handoff.",
  },
  {
    adapterId: "memory_map_renderer",
    title: "Memory Map Renderer",
    adapterKind: "memory_map_renderer",
    supportedRenderModes: ["memory_map_view"],
    supportedTargetZones: ["center_viewport", "right_context"],
    centerViewportCompatible: true,
    appTsxHardcodingAllowed: false,
    directEngineBindingAllowed: false,
    bindingPolicy: "adapter_boundary_only",
    safetyMode: "read_only_visualization",
    description: "Memory map renderer for layered memory, folder sequence and governance visibility.",
  },
  {
    adapterId: "three_d_scene_renderer",
    title: "3D Scene Renderer Adapter",
    adapterKind: "three_d_scene_renderer",
    supportedRenderModes: ["three_d_scene_adapter"],
    supportedTargetZones: ["center_viewport"],
    centerViewportCompatible: true,
    appTsxHardcodingAllowed: false,
    directEngineBindingAllowed: false,
    bindingPolicy: "adapter_boundary_only",
    safetyMode: "guarded_interactive_preview",
    description: "3D renderer adapter for dashboard data visualization, CAD/CAM and scene rendering.",
  },
  {
    adapterId: "simulation_scene_renderer",
    title: "Simulation Scene Renderer Adapter",
    adapterKind: "simulation_scene_renderer",
    supportedRenderModes: ["simulation_scene_adapter"],
    supportedTargetZones: ["center_viewport"],
    centerViewportCompatible: true,
    appTsxHardcodingAllowed: false,
    directEngineBindingAllowed: false,
    bindingPolicy: "adapter_boundary_only",
    safetyMode: "guarded_interactive_preview",
    description: "Simulation renderer adapter for physics, robotics, digital twin and sandbox scenes.",
  },
  {
    adapterId: "external_placeholder_renderer",
    title: "External Placeholder Renderer",
    adapterKind: "external_placeholder_renderer",
    supportedRenderModes: ["external_adapter_placeholder"],
    supportedTargetZones: ["center_viewport", "right_context"],
    centerViewportCompatible: true,
    appTsxHardcodingAllowed: false,
    directEngineBindingAllowed: false,
    bindingPolicy: "adapter_boundary_only",
    safetyMode: "read_only_visualization",
    description: "Reserved placeholder renderer for future external dashboard adapters.",
  },
];
