from __future__ import annotations

SECURITY_LAYER_ADAPTERS_PACKAGE_ID = "MAKSIMAR_SERVER_SECURITY_LAYER_ADAPTERS"
SECURITY_LAYER_ADAPTERS_BATCH_ID = "PHASE_1_BATCH_1_4"
SECURITY_LAYER_ADAPTERS_DIRECT_EXECUTION_ALLOWED = False
SECURITY_LAYER_ADAPTERS_RUNTIME_MUTATION_ALLOWED = False
SECURITY_LAYER_ADAPTERS_CANONICAL_WRITE_ALLOWED = False

__all__ = [
    "SECURITY_LAYER_ADAPTERS_PACKAGE_ID",
    "SECURITY_LAYER_ADAPTERS_BATCH_ID",
    "SECURITY_LAYER_ADAPTERS_DIRECT_EXECUTION_ALLOWED",
    "SECURITY_LAYER_ADAPTERS_RUNTIME_MUTATION_ALLOWED",
    "SECURITY_LAYER_ADAPTERS_CANONICAL_WRITE_ALLOWED",
]
