from __future__ import annotations

SECURITY_LAYER_ID = "SECURITY_LAYER"
SECURITY_LAYER_KIND = "foundation_security_layer"
SECURITY_LAYER_BATCH_ID = "PHASE_1_BATCH_1_1"
SECURITY_LAYER_SURFACE_READY = True
SECURITY_LAYER_RUNTIME_ENFORCEMENT_ENABLED = False
SECURITY_LAYER_RUNTIME_MUTATION_ALLOWED = False
SECURITY_LAYER_CANONICAL_WRITE_ALLOWED = False
SECURITY_LAYER_DIRECT_EXECUTION_ALLOWED = False
SECURITY_LAYER_DASHBOARD_MUTATION_ALLOWED = False

__all__ = [
    "SECURITY_LAYER_ID",
    "SECURITY_LAYER_KIND",
    "SECURITY_LAYER_BATCH_ID",
    "SECURITY_LAYER_SURFACE_READY",
    "SECURITY_LAYER_RUNTIME_ENFORCEMENT_ENABLED",
    "SECURITY_LAYER_RUNTIME_MUTATION_ALLOWED",
    "SECURITY_LAYER_CANONICAL_WRITE_ALLOWED",
    "SECURITY_LAYER_DIRECT_EXECUTION_ALLOWED",
    "SECURITY_LAYER_DASHBOARD_MUTATION_ALLOWED",
]
