from __future__ import annotations

from typing import Dict, Tuple


def build_history_track_canonical_mapping() -> Dict[str, Tuple[str, ...]]:
    return {
        "H0_foundation_boundary": (
            "history_boundary_models.py",
            "history_ingestion_builders.py",
            "history_scope_models.py",
        ),
        "H1_source_intake": (
            "archive_source_models.py",
            "archive_source_metadata_models.py",
            "archive_source_builders.py",
            "archive_source_reader.py",
            "archive_source_validators.py",
            "source_type_models.py",
        ),
        "H2_format_adapter_layer": (
            "adapter_base.py",
            "adapter_registry_models.py",
            "adapter_registry_builder.py",
            "html_adapter.py",
            "pdf_adapter.py",
            "txt_adapter.py",
            "md_adapter.py",
            "json_adapter.py",
        ),
        "H3_extraction_layer": (
            "extracted_document_models.py",
            "extracted_content_models.py",
            "extraction_builders.py",
            "extraction_summary_builder.py",
            "extraction_validators.py",
            "unified_extraction_reader.py",
            "message_extractor.py",
        ),
        "H4_fingerprint_dedup_layer": (
            "fingerprint_models.py",
            "file_fingerprint_builder.py",
            "content_fingerprint_builder.py",
            "unit_fingerprint_builder.py",
            "fingerprint_registry_models.py",
            "fingerprint_registry_builder.py",
            "fingerprint_validators.py",
            "dedup_models.py",
            "dedup_validators.py",
            "dedup_builders.py",
            "dedup_decision_summary_builder.py",
            "file_duplicate_detector.py",
            "content_duplicate_detector.py",
            "unit_duplicate_detector.py",
            "incremental_import_resolver.py",
        ),
        "H5_segmentation_layer": (
            "segmentation_models.py",
            "segmentation_builders.py",
            "segmentation_validators.py",
            "chat_segmenter.py",
            "document_section_segmenter.py",
        ),
        "H6_import_manifest_layer": (
            "import_session_models.py",
            "import_session_registry_writer.py",
            "import_session_validators.py",
            "archive_manifest_models.py",
            "archive_manifest_builder.py",
            "archive_manifest_writer.py",
        ),
        "H7_memory_object_layer": (
            "memory_id_models.py",
            "memory_id_allocator.py",
            "memory_type_models.py",
            "memory_status_models.py",
            "truth_level_models.py",
            "project_area_models.py",
            "memory_object_models.py",
            "memory_object_builders.py",
            "memory_object_summary_builder.py",
            "memory_object_validators.py",
            "historical_memory_object_builder.py",
        ),
        "H8_graph_relation_timeline_layer": (
            "storage_node_id_models.py",
            "storage_node_models.py",
            "storage_node_builder.py",
            "graph_id_allocator.py",
            "relation_id_models.py",
            "relation_models.py",
            "relation_edge_models.py",
            "relation_builders.py",
            "relation_validators.py",
            "timeline_models.py",
            "timeline_builder.py",
            "affected_file_binding_models.py",
            "memory_test_binding_models.py",
        ),
        "H9_normalized_history_layer": (
            "normalized_history_models.py",
            "normalized_history_builders.py",
            "normalized_history_reader.py",
            "normalized_history_writer.py",
            "normalized_history_summary_builder.py",
            "normalized_history_validators.py",
        ),
        "H10_H12_storage_portability_layer": (
            "storage_root_models.py",
            "portable_storage_reference_models.py",
            "storage_layout_builders.py",
            "storage_layout_validators.py",
            "storage_relocation_builder.py",
            "nas_storage_reference_builder.py",
        ),
        "H13_projection_traceability_layer": (
            "panel_projection_models.py",
            "panel_projection_builder.py",
            "filter_projection_models.py",
            "filter_projection_builder.py",
            "traceability_models.py",
            "traceability_summary_builder.py",
        ),
        "H14_jarvis_read_layer": (
            "jarvis_history_read_models.py",
            "jarvis_history_context_reader.py",
            "jarvis_history_query_models.py",
            "jarvis_history_query_reader.py",
            "jarvis_history_summary_builder.py",
        ),
        "H15_completion_layer": (
            "history_completion_models.py",
            "history_completion_builder.py",
            "history_completion_summary_builder.py",
            "history_completion_validators.py",
        ),
        "support_only_noncanonical_helpers": (
            "__init__.py",
            "end_to_end_dry_run_models.py",
            "end_to_end_dry_run_builder.py",
            "end_to_end_dry_run_summary_builder.py",
            "end_to_end_dry_run_validators.py",
        ),
    }


def build_history_track_freeze_manifest() -> Dict[str, object]:
    mapping = build_history_track_canonical_mapping()
    return {
        "track_name": "project_history_ingestion_track",
        "freeze_ready": True,
        "canonical_phase_count": 12,
        "support_phase_count": 1,
        "canonical_mapping": mapping,
    }
