from __future__ import annotations

DATA_PLANE_SERVER_PACKAGE_ID = "MAKSIMAR_SERVER_DATA_PLANE"
DATA_PLANE_SERVER_PHASE_ID = "PHASE_2_DATA_PLANE_FOUNDATION_V1"
DATA_PLANE_SERVER_BATCH_ID = "BATCH_2_1"

DATA_PLANE_SERVER_SURFACE_DECLARED = True
DATA_PLANE_SERVER_CONTAINER_RUNTIME_ENABLED = False
DATA_PLANE_SERVER_DIRECT_EXECUTION_ALLOWED = False
DATA_PLANE_SERVER_DASHBOARD_MUTATION_ALLOWED = False
DATA_PLANE_SERVER_DIRECT_CANONICAL_WRITE_ALLOWED = False
DATA_PLANE_SERVER_HEAVY_PAYLOAD_IN_CONTROL_PATH_ALLOWED = False

__all__ = [
    "DATA_PLANE_SERVER_PACKAGE_ID",
    "DATA_PLANE_SERVER_PHASE_ID",
    "DATA_PLANE_SERVER_BATCH_ID",
    "DATA_PLANE_SERVER_SURFACE_DECLARED",
    "DATA_PLANE_SERVER_CONTAINER_RUNTIME_ENABLED",
    "DATA_PLANE_SERVER_DIRECT_EXECUTION_ALLOWED",
    "DATA_PLANE_SERVER_DASHBOARD_MUTATION_ALLOWED",
    "DATA_PLANE_SERVER_DIRECT_CANONICAL_WRITE_ALLOWED",
    "DATA_PLANE_SERVER_HEAVY_PAYLOAD_IN_CONTROL_PATH_ALLOWED",
]
